<a href="https://colab.research.google.com/github/slasher2m/slasher2m/blob/main/my_regression_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd # Для работы с данными
import scipy.stats # При работе со статистикой
import matplotlib.pyplot as plt  # Библиотека для визуализации результатов 


In [5]:
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',header=None,names=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','class']) 
data.head()

age          workclass  fnlwgt  ... hours-per-week  native-country   class
0   39          State-gov   77516  ...             40   United-States   <=50K
1   50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2   38            Private  215646  ...             40   United-States   <=50K
3   53            Private  234721  ...             40   United-States   <=50K
4   28            Private  338409  ...             40            Cuba   <=50K

[5 rows x 15 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   39              32560 non-null  int64 
 1    State-gov      32560 non-null  object
 2    77516          32560 non-null  int64 
 3    Bachelors      32560 non-null  object
 4    13             32560 non-null  int64 
 5    Never-married  32560 non-null  object
 6    Adm-clerical   32560 non-null  object
 7    Not-in-family  32560 non-null  object
 8    White          32560 non-null  object
 9    Male           32560 non-null  object
 10   2174           32560 non-null  int64 
 11   0              32560 non-null  int64 
 12   40             32560 non-null  int64 
 13   United-States  32560 non-null  object
 14   <=50K          32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [7]:
data[ pd.isnull(data['class'])].head()
data['class'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [8]:
from sklearn.linear_model import LogisticRegression

In [33]:
selectedColumns = data [['age', 'sex','class']]

In [34]:
X = pd.get_dummies (selectedColumns, columns = ['sex'])
del X['class']
X.head()

age  sex_ Female  sex_ Male
0   39            0          1
1   50            0          1
2   38            0          1
3   53            0          1
4   28            1          0

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit( data['class'])
LabelEncoder()
le.classes_

array([' <=50K', ' >50K'], dtype=object)

In [36]:
y = pd.Series (data = le.transform(data['class']))
y.head()

0    0
1    0
2    0
3    0
4    0
dtype: int64

In [37]:
from sklearn.pipeline import make_pipeline # используем пайплайны для удобства
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 

model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))

In [38]:
model = LogisticRegression() 

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [40]:
model.fit(X_train, y_train)
predictions = model.predict(X_test)

In [41]:
predictions[:5]

array([0, 0, 0, 0, 0])

In [42]:
model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [43]:
model.predict_proba(X_test)

array([[0.9297044 , 0.0702956 ],
       [0.86719005, 0.13280995],
       [0.78062425, 0.21937575],
       ...,
       [0.81235241, 0.18764759],
       [0.55245133, 0.44754867],
       [0.66398991, 0.33601009]])

In [44]:
model.score(X_train, y_train)

0.7396893646893646

In [45]:
model.score(X_test,y_test)

0.7472617463404647

In [46]:
from sklearn.svm import SVC
# используем пайплайны
clf = make_pipeline(StandardScaler(), SVC(gamma='auto')) 
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svc',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=3,
                     gamma='auto', kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [47]:
clf.score(X_train, y_train)

0.7575026325026325

In [48]:
clf.score(X_test, y_test)

0.7631282628723514

In [49]:
svc = SVC(gamma='auto')
svc.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [50]:
svc.score(X_train, y_train)

0.7589066339066339

In [51]:
svc.score(X_test, y_test)

0.7624117105128467